#!/bin/sh
#
# i-MSCP ConfigScript Debian
# Version: 0.4
# License: GPLv2
# Author : i-MSCP Team, DragonZX
# Credits: i-MSCP Development Team
#----------------------------------
# Varibles and functions

read -p 'Which version of i-MSCP do you want to install (i.e. 1.2.0)? :' version

echo '
--------------------------------
Welcome to i-MSCP installation.
--------------------------------
Choose what you want to do:
1) Install an i-MSCP 
2) Reconfigure i-MSCP
3) Debug mode
4) Uninstall an i-MSCP
5) Full backup of i-MSCP (experimental)
6) Full restore of i-MSCP (experimental)
7) Exit the installer' 
read -p "Enter your choice [1-7] " choice
# Installation of a version
if [ $choice -eq 1 ] ; then
    #==== Start i-MSCP installer ====
	aptitude update && aptitude -y safe-upgrade
    aptitude -y install bzip2 wget tar ca-sertificates xz-utils
    perl /usr/local/src/imscp/imscp-$version/imscp-autoinstall "$@"
    exit			
	# Redownload i-MSCP
elif [ $choice -eq 2 ] ; then
	rm -fR /usr/local/src/imscp/
    mkdir -p /usr/local/src/imscp
    cd /usr/local/src/imscp
    aptitude update && aptitude -y safe-upgrade
    aptitude -y install bzip2 wget tar ca-sertificates xz-utils
	echo '#### DOWNLOADING the latest i-MSCP version ####'
    wget https://github.com/i-MSCP/imscp/archive/$version.tar.gz
    tar xvfz $version.tar.gz
    cd imscp-$version
    #==== Start i-MSCP installer ====
    perl imscp-autoinstall -r
    exit			
	# Uninsall i-MSCP
elif [ $choice -eq 3 ] ; then
	rm -fR /usr/local/src/imscp/
	mkdir -p /usr/local/src/imscp
    cd /usr/local/src/imscp
    aptitude update && aptitude -y safe-upgrade
    aptitude -y install bzip2 wget tar ca-sertificates xz-utils
	echo '#### DOWNLOADING the latest i-MSCP version version ####'
    wget https://github.com/i-MSCP/imscp/archive/$version.tar.gz
    tar xvfz $version.tar.gz
    cd imscp-$version
    #==== Start i-MSCP installer ====
    perl imscp-autoinstall -d
    exit			
	# Uninsall i-MSCP
elif [ $choice -eq 4 ] ; then
	echo '#### UNINSTALLING an i-MSCP ####'
    cd /var/www/imscp/engine/setup
    perl imscp-uninstall
    exit
elif [ $choice -eq 5 ] ; then
	echo '#### Backuping an i-MSCP ####'
	read -p 'Please enter the MySQL root password: ' mypass
	mkdir /tmp/imscpbkp
	cd /tmp/imscpbkp
	mysqldump -u root --password=$mypass --all-databases > imscp.sql
	tar cvfj www.txz /var/www/virtual
	tar cvfj mail.txz /var/mail/virtual
	tar cvfj config.txz /etc/imscp 
	cd ..
	tar cvf imscp.bkp imscpbkp
	cp imscp.bkp /root/imscp.bkp
	echo Take it from root directory
	cd /root
	exit
elif [ $choice -eq 6 ] ; then
	echo '#### Restoring an i-MSCP ####'
	read -p 'Please enter the MySQL root password: ' mypass
	mkdir /tmp/imscpbkp
	cp /root/imscp.bkp /tmp/imscp.bkp
	tar xvf imscp.bkp
	cd /tmp/imscpbkp
	tar xvfj www.txz -c /var/www/virtual
	tar xvfj mail.txz -c /var/mail/virtual
	tar xvfj config.txz -c /etc/imscp 
	mysql -u root --password=$mypass < imscp.sql
	rm f /root/imscp.bkp
	cd /root
	echo Restoring complete
	exit
else
exit
fi
