#!/bin/bash
#Initialisation
read -p 'Which major version of the kernel do you want to install (2-4)?: ' gen
if [$gen -eq ""]; then
gen='4'
elif [$gen -eq 2]; then
read -p 'Which version of the kernel do you want to install (recomended 2.6.32.65)?: ' ver
if [$ver -eq ""]; then
ver='2.6.32.65'
fi
link="https://www.kernel.org/pub/linux/kernel/v2.6/longterm/v2.6.32/linux-$ver.tar.xz"
else
read -p "Which version of the kernel do you want to install (at least $gen.0.1)?: " ver
if [$ver -eq ""]; then
ver="$gen.0.1"
fi
link="https://www.kernel.org/pub/linux/kernel/v$gen.x/linux-$ver.tar.xz"
fi
read -p 'Skip the download [y/N] ' skip
read -p 'Do you want to install developer packages? [y/N] ' dev
read -p 'Do you want to reconfigure the kernel manually? [y/N] ' manual
read -p 'Do you want to remove the kernel after installation? [y/N] ' remdeb
#working
case $dev in
	y|Y)  apt-get -y install make kernel-package libncurses5-dev fakeroot wget build-essential bc ;;
	n|N|*)  echo "Developer package installation has been skipped" ;;
esac
cd /usr/src
case $skip in
	y|Y)  echo "Sources download has been skipped" ;;
	n|N|*)  wget --secure-protocol=auto $link ;;
esac
echo Installing linux kernel $ver
tar xvf linux-$ver.tar.xz
rm linux
ln -s linux-$ver linux
cd /usr/src/linux
cp /boot/config-`uname -r` ./.config
make oldconfig
case $manual in
	y|Y)  make menuconfig ;;
	n|N|*)  echo "Configuration is based on the old config" ;;
esac
make-kpkg clean
fakeroot make-kpkg --initrd kernel_image kernel_headers kernel_doc kernel_source
cd /usr/src
dpkg -i linux-headers-$ver*.deb
dpkg -i linux-image-$ver*.deb
dpkg -i linux-doc-$ver*.deb

case $remdeb in
	y|Y)  rm -f *.deb ;;
	n|N|*)  echo "Your *.deb files in the /usr/src" ;;
esac
exit
