#!/bin/bash
read -p 'Which version of the kernel do you want to install (at least 3.0.0)?: ' ver
read -p 'Skip the download [y/N] ' skip
read -p 'Do you want to install developer packages? [y/N] ' dev
read -p 'Do you want to reconfigure the kernel manually? [y/N] ' manual
read -p 'Do you want to remove the kernel after installation? [y/N] ' remdeb
case $dev in
	y|Y*)  apt-get -y install make kernel-package libncurses5-dev fakeroot wget build-essential bc ;;
	n|N*)  echo "Developer package installation has been skipped" ;;
	*) echo "Developer package installation has been skipped" ;;
esac
echo Installing linux kernel $ver
cd /usr/src
case $skip in
	y|Y*)  echo "Sources download has been skipped" ;;
	n|N*)  wget kernel.org/pub/linux/kernel/v3.x/linux-$ver.tar.xz ;;
	*) wget kernel.org/pub/linux/kernel/v3.x/linux-$ver.tar.xz ;;
esac
tar xvf linux-$ver.tar.xz
rm linux
ln -s linux-$ver linux
cd /usr/src/linux
cp /boot/config-`uname -r` ./.config
make oldconfig
case $manual in
	y|Y*)  make menuconfig ;;
	n|N*)  echo "Configuration is based on the old config" ;;
	*) echo "Configuration is based on the old config" ;;
esac
make-kpkg clean
fakeroot make-kpkg --initrd kernel_image kernel_headers kernel_doc kernel_source
cd /usr/src
dpkg -i linux-image*.deb
case $remdeb in
	y|Y*)  rm -f *.deb ;;
	n|N*)  echo "Your *.deb files in the /usr/src" ;;
	*) echo "Your *.deb files in the /usr/src" ;;
esac
exit
